#!/usr/bin/env python3
"""
Magnetic Field Scanner - Log Analyzer
Version: v1.1.0

Parses live field operation logs (_log.csv) generated by the Wand's SD card.
Outputs a synchronized 3-pane matplotlib dashboard showing Gradient Magnitude, 
Audio Frequency response, and IMU Gyroscope Z-axis (Yaw) to visually correlate 
physical sweeping motions with underground utility strikes.
"""

import argparse
import pandas as pd
import matplotlib.pyplot as plt
import os
import sys

def analyze_log(input_file, output_file, max_mag):
    # Windows path bulletproofing: strip accidental terminal quotes and normalize slashes
    input_file = os.path.normpath(input_file.strip('\'"'))
    output_file = os.path.normpath(output_file.strip('\'"'))

    if not os.path.exists(input_file):
        print(f"Error: File '{input_file}' not found.")
        sys.exit(1)

    print(f"Analyzing log file: {input_file}")
    df = pd.read_csv(input_file)

    # Convert time_ms to relative seconds
    df['time_sec'] = (df['time_ms'] - df['time_ms'].iloc[0]) / 1000.0

    # Filter out massive EMI glitches for visual clarity of real targets
    clean_df = df[df['mag'] < max_mag]

    # Create 4 subplots
    fig, (ax1, ax2, ax3, ax4) = plt.subplots(4, 1, figsize=(14, 12), sharex=True)

    # Plot 1: Gradient Magnitude
    ax1.plot(clean_df['time_sec'], clean_df['mag'], color='b', linewidth=1)
    ax1.set_ylabel("Gradient (counts)", fontsize=11)
    ax1.set_title(f"Magnetic Gradient over Time ({os.path.basename(input_file)})", fontsize=14)
    ax1.grid(True, alpha=0.3)

    # Plot 2: Audio Frequency
    ax2.plot(clean_df['time_sec'], clean_df['freq'], color='r', linewidth=1, label='Target Freq')
    ax2.set_ylabel("Audio (Hz)", fontsize=11, color='r')
    ax2.tick_params(axis='y', labelcolor='r')
    ax2.grid(True, alpha=0.3)
    
    if 'audio_gain' in clean_df.columns:
        ax2_gain = ax2.twinx()
        ax2_gain.plot(clean_df['time_sec'], clean_df['audio_gain'], color='green', linewidth=1, alpha=0.5, linestyle='--', label='Audio Gain')
        ax2_gain.set_ylabel("Gain Multiplier", fontsize=11, color='green')
        ax2_gain.tick_params(axis='y', labelcolor='green')

    # Plot 3: IMU Gyroscope Data (The Sweep Motion)
    ax3.plot(clean_df['time_sec'], clean_df['gyrX'], label='Gyro X (Pitch/Roll)', alpha=0.7)
    ax3.plot(clean_df['time_sec'], clean_df['gyrY'], label='Gyro Y (Pitch/Roll)', alpha=0.7)
    ax3.plot(clean_df['time_sec'], clean_df['gyrZ'], label='Gyro Z (Sweep Yaw)', alpha=0.9, color='purple', linewidth=1.5)
    ax3.set_ylabel("Gyro (deg/sec)", fontsize=11)
    ax3.set_title("Physical Sweeping Motion (IMU Gyroscope)", fontsize=12)
    ax3.legend(loc="upper right")
    ax3.grid(True, alpha=0.3)
    
    # Plot 4: Madgwick Quaternions (if present)
    if 'QW' in clean_df.columns:
        ax4.plot(clean_df['time_sec'], clean_df['QW'], label='QW', alpha=0.8)
        ax4.plot(clean_df['time_sec'], clean_df['QX'], label='QX', alpha=0.8)
        ax4.plot(clean_df['time_sec'], clean_df['QY'], label='QY', alpha=0.8)
        ax4.plot(clean_df['time_sec'], clean_df['QZ'], label='QZ', alpha=0.8)
        ax4.set_ylabel("Quaternion", fontsize=11)
        ax4.set_title("Madgwick Sensor Fusion (AHRS)", fontsize=12)
        ax4.legend(loc="upper right")
        ax4.grid(True, alpha=0.3)
    else:
        ax4.text(0.5, 0.5, "Quaternions not available in this log", ha='center', va='center')
        
    ax4.set_xlabel("Time (seconds)", fontsize=12)

    plt.tight_layout()
    plt.savefig(output_file, dpi=150)
    print(f"Success! Plot saved to {output_file}")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Analyze and visualize Wand field logs.")
    parser.add_argument("-i", "--input", required=True, help="Input CSV log file (e.g., _log.csv)")
    parser.add_argument("-o", "--output", default="log_analysis_plot.png", help="Output plot image file (default: log_analysis_plot.png)")
    parser.add_argument("-m", "--max-mag", type=float, default=10000.0, help="Maximum gradient magnitude to display (filters EMI outliers, default: 10000)")
    
    args = parser.parse_args()
    analyze_log(args.input, args.output, args.max_mag)
